CRITICAL - 2023-03-06 06:14:08 --> Invalid file: "v_peta.php"
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('v_peta.php')
 2 SYSTEMPATH\Common.php(1184): CodeIgniter\View\View->render('v_peta', [], true)
 3 APPPATH\Controllers\Home.php(9): view('v_peta')
 4 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->index()
 5 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 6 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-06 07:23:52 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;postgres&quot; in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(75): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\petalokasiobjek\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\petalokasiobjek\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\petalokasiobjek\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\petalokasiobjek\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\petalokasiobjek\app\Controllers\Home.php(36): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(934): App\Controllers\Home->simpan_tambah_data()
#11 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#12 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\petalokasiobjek\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2023-03-06 07:23:52 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;postgres&quot;
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "datalokasiobjek" ("nama", "deskripsi", "latitude", "longitude", "created_at", "updated_at") VALUES (:nama:, :deskripsi:, :latitude:, :longitude:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Home.php(36): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->simpan_tambah_data()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-06 07:27:54 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;postgres&quot; in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(75): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\petalokasiobjek\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\petalokasiobjek\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\petalokasiobjek\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\petalokasiobjek\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\petalokasiobjek\app\Controllers\Home.php(36): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(934): App\Controllers\Home->simpan_tambah_data()
#11 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#12 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\petalokasiobjek\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2023-03-06 07:27:54 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;postgres&quot;
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "datalokasiobjek" ("nama", "deskripsi", "latitude", "longitude", "created_at", "updated_at") VALUES (:nama:, :deskripsi:, :latitude:, :longitude:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Home.php(36): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->simpan_tambah_data()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-06 07:29:05 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;postgres&quot; in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(75): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\petalokasiobjek\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\petalokasiobjek\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\petalokasiobjek\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\petalokasiobjek\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\petalokasiobjek\app\Controllers\Home.php(36): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(934): App\Controllers\Home->simpan_tambah_data()
#11 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#12 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\petalokasiobjek\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2023-03-06 07:29:05 --> Unable to connect to the database.
Main connection [Postgre]: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user &quot;postgres&quot;
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "datalokasiobjek" ("nama", "deskripsi", "latitude", "longitude", "created_at", "updated_at") VALUES (:nama:, :deskripsi:, :latitude:, :longitude:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Home.php(36): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->simpan_tambah_data()
 9 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
10 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
ERROR - 2023-03-06 07:30:01 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user "postgres" in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(75): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SELECT "table_n...')
#5 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
#6 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#7 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(706): CodeIgniter\Database\MigrationRunner->ensureTable()
#8 C:\xampp\htdocs\petalokasiobjek\system\Commands\Database\MigrateRollback.php(89): CodeIgniter\Database\MigrationRunner->getLastBatch()
#9 C:\xampp\htdocs\petalokasiobjek\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#11 C:\xampp\htdocs\petalokasiobjek\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
ERROR - 2023-03-06 07:30:44 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user "postgres" in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(75): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SELECT "table_n...')
#5 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
#6 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#7 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(706): CodeIgniter\Database\MigrationRunner->ensureTable()
#8 C:\xampp\htdocs\petalokasiobjek\system\Commands\Database\MigrateRollback.php(89): CodeIgniter\Database\MigrationRunner->getLastBatch()
#9 C:\xampp\htdocs\petalokasiobjek\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#11 C:\xampp\htdocs\petalokasiobjek\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
ERROR - 2023-03-06 07:32:58 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user "postgres" in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(75): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SELECT "table_n...')
#5 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
#6 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#7 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(706): CodeIgniter\Database\MigrationRunner->ensureTable()
#8 C:\xampp\htdocs\petalokasiobjek\system\Commands\Database\MigrateRollback.php(89): CodeIgniter\Database\MigrationRunner->getLastBatch()
#9 C:\xampp\htdocs\petalokasiobjek\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#11 C:\xampp\htdocs\petalokasiobjek\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
ERROR - 2023-03-06 07:42:48 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user "postgres" in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(75): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SELECT "table_n...')
#5 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
#6 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#7 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(168): CodeIgniter\Database\MigrationRunner->ensureTable()
#8 C:\xampp\htdocs\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\petalokasiobjek\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\petalokasiobjek\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
ERROR - 2023-03-06 07:48:31 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user "postgres" in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(75): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SELECT "table_n...')
#5 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
#6 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#7 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(168): CodeIgniter\Database\MigrationRunner->ensureTable()
#8 C:\xampp\htdocs\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\petalokasiobjek\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\petalokasiobjek\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
ERROR - 2023-03-06 07:49:23 --> Error connecting to the database: ErrorException: pg_connect(): Unable to connect to PostgreSQL server: FATAL:  password authentication failed for user "postgres" in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:75
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_connect(): U...', 'C:\\xampp\\htdocs...', 75)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(75): pg_connect('host=localhost ...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(391): CodeIgniter\Database\Postgre\Connection->connect(false)
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1408): CodeIgniter\Database\BaseConnection->query('SELECT "table_n...')
#5 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(1427): CodeIgniter\Database\BaseConnection->listTables()
#6 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(768): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#7 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(168): CodeIgniter\Database\MigrationRunner->ensureTable()
#8 C:\xampp\htdocs\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\petalokasiobjek\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\petalokasiobjek\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
INFO - 2023-03-06 08:27:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:27:11 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-03-06 08:37:09 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for type numeric: &quot;&quot;
LINE 1: ...ude&quot;, &quot;created_at&quot;, &quot;updated_at&quot;) VALUES ('', '', '', '', '2...
                                                             ^ in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 147)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(147): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(691): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\petalokasiobjek\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\petalokasiobjek\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\petalokasiobjek\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\petalokasiobjek\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\petalokasiobjek\app\Controllers\Home.php(37): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(934): App\Controllers\Home->simpan_tambah_data()
#11 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#12 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\petalokasiobjek\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2023-03-06 08:37:09 --> pg_query(): Query failed: ERROR:  invalid input syntax for type numeric: &quot;&quot;
LINE 1: ...ude&quot;, &quot;created_at&quot;, &quot;updated_at&quot;) VALUES ('', '', '', '', '2...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "datalokasiobjek" ("nama", "deskripsi", "latitude", "longitude", "created_at", "updated_at") VALUES (:nama:, :deskripsi:, :latitude:, :longitude:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(37): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->simpan_tambah_data()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-03-06 08:37:13 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:37:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:37:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:40:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:40:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:40:22 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:40:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:40:56 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:41:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:41:39 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:48:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:48:10 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:50:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:50:05 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2023-03-06 08:50:39 --> ErrorException: pg_query(): Query failed: ERROR:  invalid input syntax for type numeric: &quot;&quot;
LINE 1: ...ude&quot;, &quot;created_at&quot;, &quot;updated_at&quot;) VALUES ('', '', '', '', '2...
                                                             ^ in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 147)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(147): pg_query(Object(PgSql\Connection), 'INSERT INTO "da...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(691): CodeIgniter\Database\Postgre\Connection->execute('INSERT INTO "da...')
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO "da...')
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "da...', Array, false)
#5 C:\xampp\htdocs\petalokasiobjek\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#6 C:\xampp\htdocs\petalokasiobjek\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#7 C:\xampp\htdocs\petalokasiobjek\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, false)
#8 C:\xampp\htdocs\petalokasiobjek\system\BaseModel.php(692): CodeIgniter\Model->insert(Array, false)
#9 C:\xampp\htdocs\petalokasiobjek\app\Controllers\Home.php(53): CodeIgniter\BaseModel->save(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(934): App\Controllers\Home->simpan_tambah_data()
#11 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#12 C:\xampp\htdocs\petalokasiobjek\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\petalokasiobjek\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 {main}
CRITICAL - 2023-03-06 08:50:39 --> pg_query(): Query failed: ERROR:  invalid input syntax for type numeric: &quot;&quot;
LINE 1: ...ude&quot;, &quot;created_at&quot;, &quot;updated_at&quot;) VALUES ('', '', '', '', '2...
                                                             ^
in SYSTEMPATH\Database\BaseConnection.php on line 645.
 1 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO "datalokasiobjek" ("nama", "deskripsi", "latitude", "longitude", "created_at", "updated_at") VALUES (:nama:, :deskripsi:, :latitude:, :longitude:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(692): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\Home.php(53): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Home->simpan_tambah_data()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-03-06 08:50:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:54:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:54:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:56:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 08:56:41 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 09:05:02 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 09:05:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 09:06:40 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 09:07:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 09:07:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 09:08:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 09:08:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 09:08:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-03-06 09:08:33 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
